var BuffOption = require("./BuffOption");

var buffOptionsArray = [
    new BuffOption('abaddon', 'abaddon_frostmourne'),
    new BuffOption('axe', 'axe_culling_blade'),
    new BuffOption('beastmaster', 'beastmaster_inner_beast'),
    new BuffOption('bloodseeker', 'bloodseeker_bloodrage'),
    new BuffOption('bounty_hunter', 'bounty_hunter_track'),
    new BuffOption('centaur', 'centaur_stampede'),
    new BuffOption('crystal_maiden', 'crystal_maiden_brilliance_aura'),
    new BuffOption('dark_seer', 'dark_seer_surge'),
    new BuffOption('dazzle', 'dazzle_weave'),
    new BuffOption('drow_ranger', 'drow_ranger_trueshot'),
    new BuffOption('invoker', 'invoker_alacrity'),
    new BuffOption('wisp', 'wisp_tether'),
    new BuffOption('wisp', 'wisp_overcharge'),
    new BuffOption('kunkka', 'kunkka_ghostship'),
    new BuffOption('lich', 'lich_frost_armor'),
    new BuffOption('life_stealer', 'life_stealer_open_wounds'),
    new BuffOption('luna', 'luna_lunar_blessing'),
    new BuffOption('lycan', 'lycan_howl'),
    new BuffOption('magnataur', 'magnataur_empower'),
    new BuffOption('mirana', 'mirana_leap'),
    new BuffOption('ogre_magi', 'ogre_magi_bloodlust'),
    new BuffOption('omniknight', 'omniknight_guardian_angel'),
    new BuffOption('rubick', 'rubick_null_field'),
    new BuffOption('skeleton_king', 'skeleton_king_vampiric_aura'),
    new BuffOption('spirit_breaker', 'spirit_breaker_empowering_haste'),
    new BuffOption('sven', 'sven_warcry'),
    new BuffOption('sven', 'sven_gods_strength'),
    new BuffOption('treant', 'treant_living_armor'),
    new BuffOption('troll_warlord', 'troll_warlord_battle_trance'),
    new BuffOption('vengefulspirit', 'vengefulspirit_command_aura'),
    new BuffOption('npc_dota_neutral_alpha_wolf', 'alpha_wolf_critical_strike'),
    new BuffOption('npc_dota_neutral_alpha_wolf', 'alpha_wolf_command_aura'),
    new BuffOption('npc_dota_neutral_polar_furbolg_ursa_warrior', 'centaur_khan_endurance_aura'),
    new BuffOption('npc_dota_neutral_giant_wolf', 'giant_wolf_critical_strike'),
    new BuffOption('npc_dota_neutral_kobold_taskmaster', 'kobold_taskmaster_speed_aura'),
    new BuffOption('npc_dota_neutral_ogre_magi', 'ogre_magi_frost_armor'),
    new BuffOption('npc_dota_neutral_satyr_hellcaller', 'satyr_hellcaller_unholy_aura'),
    new BuffOption('npc_dota_neutral_enraged_wildkin', 'enraged_wildkin_toughness_aura'),
    new BuffOption('npc_dota_necronomicon_archer_1', 'necronomicon_archer_aoe')
]
        
module.exports = buffOptionsArray;